using System.Collections.Generic;

namespace ShowdownReplayScouter.Core.ReplayAnalyzers.LogAnalysis
{
    internal static class MegaStones
    {
        /// <summary>
        /// The item needed for every Mega Evolution and Primal Reversion.
        /// Generated from the Pokémon Showdown species data.
        /// </summary>
        public static IReadOnlyDictionary<string, string> Items { get; } =
            new Dictionary<string, string>
            {
                { "Abomasnow-Mega", "Abomasite" },
                { "Absol-Mega", "Absolite" },
                { "Absol-Mega-Z", "Absolite Z" },
                { "Aerodactyl-Mega", "Aerodactylite" },
                { "Aggron-Mega", "Aggronite" },
                { "Alakazam-Mega", "Alakazite" },
                { "Altaria-Mega", "Altarianite" },
                { "Ampharos-Mega", "Ampharosite" },
                { "Audino-Mega", "Audinite" },
                { "Banette-Mega", "Banettite" },
                { "Barbaracle-Mega", "Barbaracite" },
                { "Baxcalibur-Mega", "Baxcalibrite" },
                { "Beedrill-Mega", "Beedrillite" },
                { "Blastoise-Mega", "Blastoisinite" },
                { "Blaziken-Mega", "Blazikenite" },
                { "Camerupt-Mega", "Cameruptite" },
                { "Chandelure-Mega", "Chandelurite" },
                { "Charizard-Mega-X", "Charizardite X" },
                { "Charizard-Mega-Y", "Charizardite Y" },
                { "Chesnaught-Mega", "Chesnaughtite" },
                { "Chimecho-Mega", "Chimechite" },
                { "Clefable-Mega", "Clefablite" },
                { "Crabominable-Mega", "Crabominite" },
                { "Darkrai-Mega", "Darkranite" },
                { "Delphox-Mega", "Delphoxite" },
                { "Diancie-Mega", "Diancite" },
                { "Dragalge-Mega", "Dragalgite" },
                { "Dragonite-Mega", "Dragoninite" },
                { "Drampa-Mega", "Drampanite" },
                { "Eelektross-Mega", "Eelektrossite" },
                { "Emboar-Mega", "Emboarite" },
                { "Excadrill-Mega", "Excadrite" },
                { "Falinks-Mega", "Falinksite" },
                { "Feraligatr-Mega", "Feraligite" },
                { "Floette-Mega", "Floettite" },
                { "Froslass-Mega", "Froslassite" },
                { "Gallade-Mega", "Galladite" },
                { "Garchomp-Mega", "Garchompite" },
                { "Garchomp-Mega-Z", "Garchompite Z" },
                { "Gardevoir-Mega", "Gardevoirite" },
                { "Gengar-Mega", "Gengarite" },
                { "Glalie-Mega", "Glalitite" },
                { "Glimmora-Mega", "Glimmoranite" },
                { "Golisopod-Mega", "Golisopite" },
                { "Golurk-Mega", "Golurkite" },
                { "Greninja-Mega", "Greninjite" },
                { "Groudon-Primal", "Red Orb" },
                { "Gyarados-Mega", "Gyaradosite" },
                { "Hawlucha-Mega", "Hawluchanite" },
                { "Heatran-Mega", "Heatranite" },
                { "Heracross-Mega", "Heracronite" },
                { "Houndoom-Mega", "Houndoominite" },
                { "Kangaskhan-Mega", "Kangaskhanite" },
                { "Kyogre-Primal", "Blue Orb" },
                { "Latias-Mega", "Latiasite" },
                { "Latios-Mega", "Latiosite" },
                { "Lopunny-Mega", "Lopunnite" },
                { "Lucario-Mega", "Lucarionite" },
                { "Lucario-Mega-Z", "Lucarionite Z" },
                { "Magearna-Mega", "Magearnite" },
                { "Malamar-Mega", "Malamarite" },
                { "Manectric-Mega", "Manectite" },
                { "Mawile-Mega", "Mawilite" },
                { "Medicham-Mega", "Medichamite" },
                { "Meganium-Mega", "Meganiumite" },
                { "Metagross-Mega", "Metagrossite" },
                { "Mewtwo-Mega-X", "Mewtwonite X" },
                { "Mewtwo-Mega-Y", "Mewtwonite Y" },
                { "Pidgeot-Mega", "Pidgeotite" },
                { "Pinsir-Mega", "Pinsirite" },
                { "Pyroar-Mega", "Pyroarite" },
                { "Raichu-Mega-X", "Raichunite X" },
                { "Raichu-Mega-Y", "Raichunite Y" },
                { "Sableye-Mega", "Sablenite" },
                { "Salamence-Mega", "Salamencite" },
                { "Sceptile-Mega", "Sceptilite" },
                { "Scizor-Mega", "Scizorite" },
                { "Scolipede-Mega", "Scolipite" },
                { "Scovillain-Mega", "Scovillainite" },
                { "Scrafty-Mega", "Scraftinite" },
                { "Sharpedo-Mega", "Sharpedonite" },
                { "Skarmory-Mega", "Skarmorite" },
                { "Slowbro-Mega", "Slowbronite" },
                { "Staraptor-Mega", "Staraptite" },
                { "Starmie-Mega", "Starminite" },
                { "Steelix-Mega", "Steelixite" },
                { "Swampert-Mega", "Swampertite" },
                { "Tyranitar-Mega", "Tyranitarite" },
                { "Venusaur-Mega", "Venusaurite" },
                { "Victreebel-Mega", "Victreebelite" },
                { "Zeraora-Mega", "Zeraorite" },
                { "Zygarde-Mega", "Zygardite" },
            };
    }
}
