using System.Collections.Generic;

namespace ShowdownReplayScouter.Core.Util
{
    public static class ZStatusMoves
    {
        /// <summary>
        /// The Z-Crystal needed for the Z-powered variant ("Z-Move") of every status move, based on its type.
        /// Generated from the Pokémon Showdown move data.
        /// </summary>
        public static IReadOnlyDictionary<string, string> Crystals { get; } =
            new Dictionary<string, string>
            {
                { "Acid Armor", "Poisonium Z" },
                { "Acupressure", "Normalium Z" },
                { "After You", "Normalium Z" },
                { "Agility", "Psychium Z" },
                { "Ally Switch", "Psychium Z" },
                { "Amnesia", "Psychium Z" },
                { "Aqua Ring", "Waterium Z" },
                { "Aromatherapy", "Grassium Z" },
                { "Aromatic Mist", "Fairium Z" },
                { "Assist", "Normalium Z" },
                { "Attract", "Normalium Z" },
                { "Aurora Veil", "Icium Z" },
                { "Autotomize", "Steelium Z" },
                { "Baby-Doll Eyes", "Fairium Z" },
                { "Baneful Bunker", "Poisonium Z" },
                { "Barrier", "Psychium Z" },
                { "Baton Pass", "Normalium Z" },
                { "Belly Drum", "Normalium Z" },
                { "Bestow", "Normalium Z" },
                { "Block", "Normalium Z" },
                { "Bulk Up", "Fightinium Z" },
                { "Burning Bulwark", "Firium Z" },
                { "Calm Mind", "Psychium Z" },
                { "Camouflage", "Normalium Z" },
                { "Captivate", "Normalium Z" },
                { "Celebrate", "Normalium Z" },
                { "Charge", "Electrium Z" },
                { "Charm", "Fairium Z" },
                { "Chilly Reception", "Icium Z" },
                { "Clangorous Soul", "Dragonium Z" },
                { "Coaching", "Fightinium Z" },
                { "Coil", "Poisonium Z" },
                { "Confide", "Normalium Z" },
                { "Confuse Ray", "Ghostium Z" },
                { "Conversion", "Normalium Z" },
                { "Conversion 2", "Normalium Z" },
                { "Copycat", "Normalium Z" },
                { "Corrosive Gas", "Poisonium Z" },
                { "Cosmic Power", "Psychium Z" },
                { "Cotton Guard", "Grassium Z" },
                { "Cotton Spore", "Grassium Z" },
                { "Court Change", "Normalium Z" },
                { "Crafty Shield", "Fairium Z" },
                { "Curse", "Ghostium Z" },
                { "Dark Void", "Darkinium Z" },
                { "Decorate", "Fairium Z" },
                { "Defend Order", "Buginium Z" },
                { "Defense Curl", "Normalium Z" },
                { "Defog", "Flyinium Z" },
                { "Destiny Bond", "Ghostium Z" },
                { "Detect", "Fightinium Z" },
                { "Disable", "Normalium Z" },
                { "Doodle", "Normalium Z" },
                { "Double Team", "Normalium Z" },
                { "Dragon Cheer", "Dragonium Z" },
                { "Dragon Dance", "Dragonium Z" },
                { "Eerie Impulse", "Electrium Z" },
                { "Electric Terrain", "Electrium Z" },
                { "Electrify", "Electrium Z" },
                { "Embargo", "Darkinium Z" },
                { "Encore", "Normalium Z" },
                { "Endure", "Normalium Z" },
                { "Entrainment", "Normalium Z" },
                { "Fairy Lock", "Fairium Z" },
                { "Fake Tears", "Darkinium Z" },
                { "Feather Dance", "Flyinium Z" },
                { "Fillet Away", "Normalium Z" },
                { "Flash", "Normalium Z" },
                { "Flatter", "Darkinium Z" },
                { "Floral Healing", "Fairium Z" },
                { "Flower Shield", "Fairium Z" },
                { "Focus Energy", "Normalium Z" },
                { "Follow Me", "Normalium Z" },
                { "Foresight", "Normalium Z" },
                { "Forest's Curse", "Grassium Z" },
                { "Gastro Acid", "Poisonium Z" },
                { "Gear Up", "Steelium Z" },
                { "Geomancy", "Fairium Z" },
                { "Glare", "Normalium Z" },
                { "Grass Whistle", "Grassium Z" },
                { "Grassy Terrain", "Grassium Z" },
                { "Gravity", "Psychium Z" },
                { "Growl", "Normalium Z" },
                { "Growth", "Normalium Z" },
                { "Grudge", "Ghostium Z" },
                { "Guard Split", "Psychium Z" },
                { "Guard Swap", "Psychium Z" },
                { "Hail", "Icium Z" },
                { "Happy Hour", "Normalium Z" },
                { "Harden", "Normalium Z" },
                { "Haze", "Icium Z" },
                { "Heal Bell", "Normalium Z" },
                { "Heal Block", "Psychium Z" },
                { "Heal Order", "Buginium Z" },
                { "Heal Pulse", "Psychium Z" },
                { "Healing Wish", "Psychium Z" },
                { "Heart Swap", "Psychium Z" },
                { "Helping Hand", "Normalium Z" },
                { "Hold Hands", "Normalium Z" },
                { "Hone Claws", "Darkinium Z" },
                { "Howl", "Normalium Z" },
                { "Hypnosis", "Psychium Z" },
                { "Imprison", "Psychium Z" },
                { "Ingrain", "Grassium Z" },
                { "Instruct", "Psychium Z" },
                { "Ion Deluge", "Electrium Z" },
                { "Iron Defense", "Steelium Z" },
                { "Jungle Healing", "Grassium Z" },
                { "Kinesis", "Psychium Z" },
                { "King's Shield", "Steelium Z" },
                { "Laser Focus", "Normalium Z" },
                { "Leech Seed", "Grassium Z" },
                { "Leer", "Normalium Z" },
                { "Life Dew", "Waterium Z" },
                { "Light Screen", "Psychium Z" },
                { "Lock-On", "Normalium Z" },
                { "Lovely Kiss", "Normalium Z" },
                { "Lucky Chant", "Normalium Z" },
                { "Lunar Blessing", "Psychium Z" },
                { "Lunar Dance", "Psychium Z" },
                { "Magic Coat", "Psychium Z" },
                { "Magic Powder", "Psychium Z" },
                { "Magic Room", "Psychium Z" },
                { "Magnet Rise", "Electrium Z" },
                { "Magnetic Flux", "Electrium Z" },
                { "Mat Block", "Fightinium Z" },
                { "Me First", "Normalium Z" },
                { "Mean Look", "Normalium Z" },
                { "Meditate", "Psychium Z" },
                { "Memento", "Darkinium Z" },
                { "Metal Sound", "Steelium Z" },
                { "Metronome", "Normalium Z" },
                { "Milk Drink", "Normalium Z" },
                { "Mimic", "Normalium Z" },
                { "Mind Reader", "Normalium Z" },
                { "Minimize", "Normalium Z" },
                { "Miracle Eye", "Psychium Z" },
                { "Mirror Move", "Flyinium Z" },
                { "Mist", "Icium Z" },
                { "Misty Terrain", "Fairium Z" },
                { "Moonlight", "Fairium Z" },
                { "Morning Sun", "Normalium Z" },
                { "Mud Sport", "Groundium Z" },
                { "Nasty Plot", "Darkinium Z" },
                { "Nature Power", "Normalium Z" },
                { "Nightmare", "Ghostium Z" },
                { "No Retreat", "Fightinium Z" },
                { "Noble Roar", "Normalium Z" },
                { "Obstruct", "Darkinium Z" },
                { "Octolock", "Fightinium Z" },
                { "Odor Sleuth", "Normalium Z" },
                { "Pain Split", "Normalium Z" },
                { "Parting Shot", "Darkinium Z" },
                { "Perish Song", "Normalium Z" },
                { "Play Nice", "Normalium Z" },
                { "Poison Gas", "Poisonium Z" },
                { "Poison Powder", "Poisonium Z" },
                { "Powder", "Buginium Z" },
                { "Power Shift", "Normalium Z" },
                { "Power Split", "Psychium Z" },
                { "Power Swap", "Psychium Z" },
                { "Power Trick", "Psychium Z" },
                { "Protect", "Normalium Z" },
                { "Psych Up", "Normalium Z" },
                { "Psychic Terrain", "Psychium Z" },
                { "Psycho Shift", "Psychium Z" },
                { "Purify", "Poisonium Z" },
                { "Quash", "Darkinium Z" },
                { "Quick Guard", "Fightinium Z" },
                { "Quiver Dance", "Buginium Z" },
                { "Rage Powder", "Buginium Z" },
                { "Rain Dance", "Waterium Z" },
                { "Recover", "Normalium Z" },
                { "Recycle", "Normalium Z" },
                { "Reflect", "Psychium Z" },
                { "Reflect Type", "Normalium Z" },
                { "Refresh", "Normalium Z" },
                { "Rest", "Psychium Z" },
                { "Revival Blessing", "Normalium Z" },
                { "Roar", "Normalium Z" },
                { "Rock Polish", "Rockium Z" },
                { "Role Play", "Psychium Z" },
                { "Roost", "Flyinium Z" },
                { "Rototiller", "Groundium Z" },
                { "Safeguard", "Normalium Z" },
                { "Sand Attack", "Groundium Z" },
                { "Sandstorm", "Rockium Z" },
                { "Scary Face", "Normalium Z" },
                { "Screech", "Normalium Z" },
                { "Sharpen", "Normalium Z" },
                { "Shed Tail", "Normalium Z" },
                { "Shell Smash", "Normalium Z" },
                { "Shelter", "Steelium Z" },
                { "Shift Gear", "Steelium Z" },
                { "Shore Up", "Groundium Z" },
                { "Silk Trap", "Buginium Z" },
                { "Simple Beam", "Normalium Z" },
                { "Sing", "Normalium Z" },
                { "Sketch", "Normalium Z" },
                { "Skill Swap", "Psychium Z" },
                { "Slack Off", "Normalium Z" },
                { "Sleep Powder", "Grassium Z" },
                { "Sleep Talk", "Normalium Z" },
                { "Smokescreen", "Normalium Z" },
                { "Snatch", "Darkinium Z" },
                { "Snowscape", "Icium Z" },
                { "Soak", "Waterium Z" },
                { "Soft-Boiled", "Normalium Z" },
                { "Speed Swap", "Psychium Z" },
                { "Spicy Extract", "Grassium Z" },
                { "Spider Web", "Buginium Z" },
                { "Spikes", "Groundium Z" },
                { "Spiky Shield", "Grassium Z" },
                { "Spite", "Ghostium Z" },
                { "Splash", "Normalium Z" },
                { "Spore", "Grassium Z" },
                { "Spotlight", "Normalium Z" },
                { "Stealth Rock", "Rockium Z" },
                { "Sticky Web", "Buginium Z" },
                { "Stockpile", "Normalium Z" },
                { "Strength Sap", "Grassium Z" },
                { "String Shot", "Buginium Z" },
                { "Stuff Cheeks", "Normalium Z" },
                { "Stun Spore", "Grassium Z" },
                { "Substitute", "Normalium Z" },
                { "Sunny Day", "Firium Z" },
                { "Supersonic", "Normalium Z" },
                { "Swagger", "Normalium Z" },
                { "Swallow", "Normalium Z" },
                { "Sweet Kiss", "Fairium Z" },
                { "Sweet Scent", "Normalium Z" },
                { "Switcheroo", "Darkinium Z" },
                { "Swords Dance", "Normalium Z" },
                { "Synthesis", "Grassium Z" },
                { "Tail Glow", "Buginium Z" },
                { "Tail Whip", "Normalium Z" },
                { "Tailwind", "Flyinium Z" },
                { "Take Heart", "Psychium Z" },
                { "Tar Shot", "Rockium Z" },
                { "Taunt", "Darkinium Z" },
                { "Tearful Look", "Normalium Z" },
                { "Teatime", "Normalium Z" },
                { "Teeter Dance", "Normalium Z" },
                { "Telekinesis", "Psychium Z" },
                { "Teleport", "Psychium Z" },
                { "Thunder Wave", "Electrium Z" },
                { "Tickle", "Normalium Z" },
                { "Tidy Up", "Normalium Z" },
                { "Topsy-Turvy", "Darkinium Z" },
                { "Torment", "Darkinium Z" },
                { "Toxic", "Poisonium Z" },
                { "Toxic Spikes", "Poisonium Z" },
                { "Toxic Thread", "Poisonium Z" },
                { "Transform", "Normalium Z" },
                { "Trick", "Psychium Z" },
                { "Trick Room", "Psychium Z" },
                { "Trick-or-Treat", "Ghostium Z" },
                { "Venom Drench", "Poisonium Z" },
                { "Victory Dance", "Fightinium Z" },
                { "Water Sport", "Waterium Z" },
                { "Whirlwind", "Normalium Z" },
                { "Wide Guard", "Rockium Z" },
                { "Will-O-Wisp", "Firium Z" },
                { "Wish", "Normalium Z" },
                { "Withdraw", "Waterium Z" },
                { "Wonder Room", "Psychium Z" },
                { "Work Up", "Normalium Z" },
                { "Worry Seed", "Grassium Z" },
                { "Yawn", "Normalium Z" }
            };
    }
}
